// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBC9tkeJGlLAr3JWrv9eAXSZMYsgVn3lG0',
    appId: '1:224646200519:ios:06d4ffc4385ba4ac63d2e2',
    messagingSenderId: '224646200519',
    projectId: 'squad-game-1d87d',
    storageBucket: 'squad-game-1d87d.firebasestorage.app',
    iosBundleId: 'com.example.squadGameClient',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBORGcBRzeMGsLm30vdSMiAjbFbi30olJE',
    appId: '1:224646200519:web:de4f329b3a63a1ff63d2e2',
    messagingSenderId: '224646200519',
    projectId: 'squad-game-1d87d',
    authDomain: 'squad-game-1d87d.firebaseapp.com',
    storageBucket: 'squad-game-1d87d.firebasestorage.app',
    measurementId: 'G-W18CXP9E8Y',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBC9tkeJGlLAr3JWrv9eAXSZMYsgVn3lG0',
    appId: '1:224646200519:ios:06d4ffc4385ba4ac63d2e2',
    messagingSenderId: '224646200519',
    projectId: 'squad-game-1d87d',
    storageBucket: 'squad-game-1d87d.firebasestorage.app',
    iosBundleId: 'com.example.squadGameClient',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAvNg8-mNq3yFWD4aqFQsZUOFk0CMV18BQ',
    appId: '1:224646200519:android:eb47e25c9b36f43163d2e2',
    messagingSenderId: '224646200519',
    projectId: 'squad-game-1d87d',
    storageBucket: 'squad-game-1d87d.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBORGcBRzeMGsLm30vdSMiAjbFbi30olJE',
    appId: '1:224646200519:web:15c2a6ca7a4f656663d2e2',
    messagingSenderId: '224646200519',
    projectId: 'squad-game-1d87d',
    authDomain: 'squad-game-1d87d.firebaseapp.com',
    storageBucket: 'squad-game-1d87d.firebasestorage.app',
    measurementId: 'G-VRDMS1WX81',
  );

}